version: '2.4'
services:
  jenkins-controller:
    container_name: jenkins-controller
    build: {{ jenkins_dockerfiles_folder }}/jenkins-controller
    runtime: sysbox-runc
    restart: always
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Zurich -Djenkins.install.runSetupWizard=false -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true -Dhudson.slaves.WorkspaceList=-
      - CASC_JENKINS_CONFIG=/var/jenkins_config
    networks:
      jenkins:
    volumes:
      - jenkins-controller-home:/var/jenkins_home
      - {{ jenkins_config_folder }}:/var/jenkins_config:ro

  jenkins-ssh-agent-1:
    container_name: jenkins-ssh-agent-1
    build: {{ jenkins_dockerfiles_folder }}/jenkins-ssh-agent
    runtime: sysbox-runc
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9bKxkJIUt7As5WnjrmmU7Ht21pu9Qbt001SSU5xqNRXkkNNRh/7axo+bCSJSWzREyMcAMEP/SZa8fXQrJYhTOFnFWE3Zj2R7FZn6RnsJpgrTfX8HMBYsNgHGK7iv2iZMKdF3QM0Op/VYEznZKFVlAAV8PoNxMOpYMC0bkJmmR76lrD66dzcKBwSbn2la9ZEY9XX90BdX44lMSo6tSwxF3WVHgw6+n4pVEDoLEGyIM8L5FzvVh6elmkQu9+NOT8y26b1VM2emFQrHpdtm7iImkZqJpHe2aCyf90SXe2EjvtEDXxDhRPaRBJHgadTUdx6wOqIMVz3358Pm3uu1/ET3l rsa-key-modern-jenkins-20220602
    networks:
      jenkins:
    volumes:
      - jenkins-www:/var/www/jenkins
      - jenkins-agent-1-home:/var/jenkins/agent-1

  jenkins-ssh-agent-2:
    container_name: jenkins-ssh-agent-2
    build: {{ jenkins_dockerfiles_folder }}/jenkins-ssh-agent
    runtime: sysbox-runc
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9bKxkJIUt7As5WnjrmmU7Ht21pu9Qbt001SSU5xqNRXkkNNRh/7axo+bCSJSWzREyMcAMEP/SZa8fXQrJYhTOFnFWE3Zj2R7FZn6RnsJpgrTfX8HMBYsNgHGK7iv2iZMKdF3QM0Op/VYEznZKFVlAAV8PoNxMOpYMC0bkJmmR76lrD66dzcKBwSbn2la9ZEY9XX90BdX44lMSo6tSwxF3WVHgw6+n4pVEDoLEGyIM8L5FzvVh6elmkQu9+NOT8y26b1VM2emFQrHpdtm7iImkZqJpHe2aCyf90SXe2EjvtEDXxDhRPaRBJHgadTUdx6wOqIMVz3358Pm3uu1/ET3l rsa-key-modern-jenkins-20220602
    networks:
      jenkins:
    volumes:
      - jenkins-www:/var/www/jenkins
      - jenkins-agent-2-home:/var/jenkins/agent-2

  jenkins-caddy:
    container_name: jenkins-caddy
    image: caddy:2.4.6
    restart: always
    networks:
      jenkins:
    volumes:
      - {{ jenkins_caddy_folder }}/Caddyfile:/etc/caddy/Caddyfile
      - jenkins-caddy-data:/data
      - jenkins-www:/var/www/jenkins
    ports:
      - 80:80
      - 443:443

networks:
  jenkins:

volumes:
  jenkins-controller-home:
  jenkins-agent-1-home:
  jenkins-agent-2-home:
  jenkins-www:
  jenkins-caddy-data:
